- name: 'fedk'
  num_clients: 200
  num_clients_per_task: 25
  m: 0.05
  rounds: 60
  local_step: 200
  batch_or_epoch: 'batch'
  equal_weight: false
  dataset: 'dolly'
  batch_size: 1
  max_length: 1024
  use_prompts: true
  iid: 'dir0.5'
  zerotask: 7
  dataset_subsample: 1.0
  model: 'datajuicer/LLaMA-1B-dj-refine-150B'
  lr: 3e-07
  weight_decay: 0.0
  grad_clip: -100.0
  K: 4096
  zo_eps: 0.0005
  bias_sampling: false
  bias_loss_clip: 1000.0
  grad_initial: 0.0
  device: 0
  log: false
  log_root: 'logs'
  seed: 42
  eval_metric: 'rouge'
  save: false
  r: 16
  project: 'FEDMIRA'
